name: HelloElwin
permalink: /all/:title

# Conversion
markdown            : kramdown
highlighter         : rouge
usemathjax          : true

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false


plugins:
  - jekyll-seo-tag
